// packages/web-component/src/index.ts
import { createAvatar } from '@humation/core';
import type { HumationManifest } from '@humation/core';

export type AvatarMarkupOptions = {
  seed?: string;
  selections?: Record<string, string>;
  background?: string;
  crop?: string;
  /** Rendered width; height follows the crop's aspect ratio. */
  size?: number;
  /** Accessible title. Without it the avatar is treated as decorative. */
  title?: string;
};

/**
 * Builds the <svg> markup for an avatar without any inline color style:
 * colors come from `--hm-*` CSS custom properties cascading in from the
 * surrounding document (unset slots fall back to the defaults baked into
 * the assets).
 */
export function renderAvatarMarkup(
  assets: HumationManifest,
  options: AvatarMarkupOptions = {}
): string {
  const { seed, selections, background, crop, size, title } = options;
  const data = createAvatar(assets, {
    seed,
    selections,
    background,
    crop,
  }).toRenderData();

  const { viewBox } = data;
  const width = size ?? viewBox.width;
  const height = size != null ? (size * viewBox.height) / viewBox.width : viewBox.height;
  const a11y = title
    ? `role="img"><title>${escapeText(title)}</title>`
    : 'aria-hidden="true">';
  const backgroundRect =
    data.background === 'transparent'
      ? ''
      : `<rect x="${viewBox.x}" y="${viewBox.y}" width="${viewBox.width}" height="${viewBox.height}" fill="#${data.background}" />`;

  return (
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox.x} ${viewBox.y} ${viewBox.width} ${viewBox.height}" width="${width}" height="${height}" ${a11y}` +
    backgroundRect +
    data.content +
    '</svg>'
  );
}

/**
 * Registers `<humation-avatar>` (or a custom tag name) bound to the given
 * asset set. Selection slots become attributes; colors are driven purely by
 * `--hm-*` CSS custom properties, which cascade into the shadow root:
 *
 *   defineAvatarElement(humation1);
 *   <humation-avatar seed="felix" size="96"></humation-avatar>
 *   <humation-avatar head="braids" item="calico-cat"
 *                    style="--hm-hair: #4A3728"></humation-avatar>
 */
export function defineAvatarElement(
  assets: HumationManifest,
  tagName = 'humation-avatar'
) {
  if (typeof customElements === 'undefined') {
    throw new Error('defineAvatarElement requires a DOM environment');
  }
  if (customElements.get(tagName)) return;

  const slotIds = assets.selectionSlots.map((slot) => slot.id);

  class HumationAvatarElement extends HTMLElement {
    static observedAttributes = [
      ...slotIds,
      'seed',
      'background',
      'crop',
      'size',
      'title',
    ];

    connectedCallback() {
      this.render();
    }

    attributeChangedCallback() {
      if (this.isConnected) this.render();
    }

    private render() {
      const selections: Record<string, string> = {};
      for (const id of slotIds) {
        const value = this.getAttribute(id);
        if (value) selections[id] = value;
      }

      const sizeAttr = this.getAttribute('size');
      const markup = renderAvatarMarkup(assets, {
        seed: this.getAttribute('seed') ?? undefined,
        selections,
        background: this.getAttribute('background') ?? undefined,
        crop: this.getAttribute('crop') ?? undefined,
        size: sizeAttr ? Number(sizeAttr) : undefined,
        title: this.getAttribute('title') ?? undefined,
      });

      const root = this.shadowRoot ?? this.attachShadow({ mode: 'open' });
      root.innerHTML =
        '<style>:host{display:inline-block;line-height:0}svg{display:block}</style>' +
        markup;
    }
  }

  customElements.define(tagName, HumationAvatarElement);
}

function escapeText(value: string) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

// packages/react/src/index.tsx
import { forwardRef, useMemo } from 'react';
import type { CSSProperties, SVGProps } from 'react';
import { createAvatar } from '@humation/core';
import type { HumationManifest } from '@humation/core';

export type AvatarProps = {
  /** The asset set to draw with, e.g. `humation1` from `@humation/assets-humation-1`. */
  assets: HumationManifest;
  /** Deterministic part picks per slot — same seed, same avatar. */
  seed?: string;
  /**
   * Part selections by name, alias, or canonical ID,
   * e.g. `{ head: 'braids', item: 'calico-cat' }`.
   */
  selections?: Record<string, string>;
  /**
   * Color slot values (`{ hair: '#4A3728' }`, `#` optional). Applied as CSS
   * custom properties on the <svg> element, so changing colors never
   * re-renders the avatar content; unspecified slots keep the defaults baked
   * into the assets and stay themeable from outer CSS.
   */
  colors?: Record<string, string>;
  /** Background fill (hex or 'transparent'). Defaults to the manifest default. */
  background?: string;
  /** Crop id. Defaults to the manifest default ('avatar'). */
  crop?: string;
  /** Rendered size. Numbers keep the crop's aspect ratio. */
  size?: number | string;
  /** Accessible title. Without it the avatar is treated as decorative. */
  title?: string;
} & Omit<SVGProps<SVGSVGElement>, 'children'>;

export const Avatar = forwardRef<SVGSVGElement, AvatarProps>(function Avatar(
  {
    assets,
    seed,
    selections,
    colors,
    background,
    crop,
    size,
    title,
    style,
    ...rest
  },
  ref
) {
  const selectionsKey = JSON.stringify(selections ?? null);

  const data = useMemo(
    () => createAvatar(assets, { seed, selections, background, crop }).toRenderData(),
    // eslint-disable-next-line react-hooks/exhaustive-deps -- selections is keyed by value
    [assets, seed, selectionsKey, background, crop]
  );

  const colorVariables: CSSProperties = {};
  for (const [slot, value] of Object.entries(colors ?? {})) {
    (colorVariables as Record<string, string>)[`--hm-${slot}`] =
      normalizeCssColor(value);
  }

  const { viewBox } = data;
  const width = size ?? viewBox.width;
  const height =
    typeof size === 'number'
      ? (size * viewBox.height) / viewBox.width
      : typeof size === 'string'
        ? 'auto'
        : viewBox.height;

  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={`${viewBox.x} ${viewBox.y} ${viewBox.width} ${viewBox.height}`}
      width={width}
      height={height}
      role={title ? 'img' : undefined}
      aria-hidden={title ? undefined : true}
      ref={ref}
      style={{ ...colorVariables, ...style }}
      {...rest}
    >
      {title ? <title>{title}</title> : null}
      {data.background !== 'transparent' ? (
        <rect
          x={viewBox.x}
          y={viewBox.y}
          width={viewBox.width}
          height={viewBox.height}
          fill={`#${data.background}`}
        />
      ) : null}
      <g dangerouslySetInnerHTML={{ __html: data.content }} />
    </svg>
  );
});

function normalizeCssColor(value: string) {
  const trimmed = value.trim();
  return /^[0-9a-fA-F]{6}$/.test(trimmed) ? `#${trimmed}` : trimmed;
}
